# Generated by Django 5.2.8 on 2026-01-28 21:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('institution_name', models.CharField(max_length=200)),
                ('country', models.CharField(default='Nigeria', max_length=100)),
                ('currency', models.CharField(choices=[('NGN', '₦ Naira'), ('USD', '$ US Dollar')], default='NGN', max_length=3)),
                ('needs_ctb', models.BooleanField(default=True)),
                ('needs_live_classes', models.BooleanField(default=False)),
                ('primary_color', models.CharField(default='#1A237E', max_length=7)),
                ('secondary_color', models.CharField(default='#00C853', max_length=7)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='client_logos/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='Bootstrap icon class', max_length=50)),
                ('feature_type', models.CharField(choices=[('ctb', 'Computer-Based Testing'), ('LIVE', 'Live Classroom'), ('GEN', 'General')], max_length=10)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='core.client')),
            ],
        ),
    ]
