# Generated by Django 5.2.8 on 2026-01-28 21:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('institution', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('needs_ctb', models.BooleanField(default=True)),
                ('needs_live_classes', models.BooleanField(default=False)),
                ('estimated_students', models.IntegerField(default=100)),
                ('estimated_teachers', models.IntegerField(default=10)),
                ('preferred_colors', models.CharField(blank=True, max_length=200)),
                ('has_logo', models.BooleanField(default=False)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('deployment_fee', models.CharField(blank=True, max_length=100)),
                ('proposal_pdf', models.FileField(blank=True, null=True, upload_to='proposals/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('GENERATED', 'Generated'), ('SENT', 'Sent'), ('VIEWED', 'Viewed'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
